
export const settingConstants = {
    FONT_SIZE: 'SET_FONT_SIZE',
    SIDEBAR: 'SIDEBAR_VISIBILITY',
    PIN_SIDEBAR: 'SET_PIN_SIDEBAR',
    MAIN_HEADER: 'SET_MAIN_HEADER',
    RIGHT_PANEL: 'RIGHT_PANEL_VISIBILITY',
    THEME: 'SET_THEME',
    SIDEBAR_BG_IMG: 'SET_SIDEBAR_BG_IMG',
    SIDEBAR_BG_IMG_VISIBILITY: 'SIDEBAR_BG_IMG_VISIBILITY',            
    BORDER_RADIUS: 'BORDER_RADIUS_VISIBILITY'
}
