
export const UI_Constants = {
    CHANGE_FONTSIZE: 'CHANGE_FONT_SIZE',
    PAGE_TITLE: 'CHANGE_PAGE_TITLE',
    TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
    TOGGLE_PIN_SIDEBAR: 'PIN_SIDEBAR',
    SIDEBAR_HOVER: 'SIDEBAR_HOVER'
}
