
export const UI_Constants = {
    LINK_CLICK: 'ACTIVATE_LINK',
    TOGGLE_SUBMENU: 'TOGGLE_SUB_MENU',
    CHANGE_FONTSIZE: 'CHANGE_FONT_SIZE',
    TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
    TOGGLE_PIN_SIDEBAR: 'PIN_SIDEBAR',
    SIDEBAR_HOVER: 'SIDEBAR_HOVER'
}
